### ISSUE TITLE
Stub out the required files

### ISSUE THREAD

**Issue by t-fine** [open-horizon-services/service-edgelake#1]
Add:
- [x] README
- [x] LICENSE 
- [ ] Contributors
- [ ] Makefile
- [x] MAINTAINERS

A similar task was just completed for `service-kubearmor-security` if a reference is needed: 
https://github.com/open-horizon-services/service-kubearmor-security/pull/2

**Comment by t-fine** [comment]
@joewxboy here's a first issue with a reference to the files you just merged for the kubearmor service

**Comment by joewxboy** [comment]
In progress ...
