### ISSUE TITLE
Typo in EdgeLake_KubeArmor_integration.md file

### ISSUE THREAD

**Issue by joewxboy** [open-horizon-services/service-edgelake#21]
In more than one place in the EdgeLake_KubeArmor_integration.md file, service is misspelled as `servvice`.  Please go through this file and correct the typos.

**Comment by SR2090** [comment]
Hey @joewxboy  i can do this please assign it to me.

**Comment by joewxboy** [comment]
Sure, @SR2090 .  Don't forget to sign your commit: `commit -s -m "Issue 21: Typo in docs"`

**Comment by SR2090** [comment]
Hey @joewxboy I am unable to push my branch to remote. Can you give access please !

**Comment by SR2090** [comment]
Hey @joewxboy, here is the [PR](https://github.com/open-horizon-services/service-edgelake/pull/25)

**Comment by joewxboy** [comment]
Congratulations, @SR2090 .  You are now officially a Contributor!
